// <Auto-Generated/>

using Cuture.AspNetCore.DynamicCors;

namespace DynamicCorsWebApplication;

public class SampleAllowedOriginsSyncSource
    : AllowedOriginsSyncSource
{
    // string? policyName 会自动注入
    public SampleAllowedOriginsSyncSource(PolicyName policyName, ILogger<SampleAllowedOriginsSyncSource> logger, IHostApplicationLifetime applicationLifetime)
        : base(policyName)
    {
        var cancellationToken = applicationLifetime.ApplicationStopping;

        Task.Run(async () =>
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(10), cancellationToken);

                logger.LogInformation("SampleAllowedOriginsSyncSource changed");

                //通知当前源已变更，程序会自动调用 GetOrigins 再次获取
                NotifySourceChanged();
            }
        }, cancellationToken);
    }

    protected override Task<IEnumerable<string>> InnerGetOriginsAsync(CancellationToken cancellationToken)
    {
        //获取允许来源列表
        return Task.FromResult<IEnumerable<string>>(["http://*.sample3.com"]);
    }
}
